import type { ComponentType } from "react";
import {
  Activity,
  BarChart3,
  BookOpen,
  Church,
  Cloud,
  Crown,
  Film,
  Flame,
  Footprints,
  Home,
  Image,
  Info,
  Megaphone,
  Paintbrush,
  Palette,
  Scissors,
  Timer,
  TrendingUp,
  User,
  Calendar,
  FileText,
  Search,
  Globe,
  ShoppingCart,
  ShoppingBag,
  UtensilsCrossed,
  Building2,
  HeartPulse,
  Heart,
  MapPin,
  Phone,
  Navigation,
  MoreHorizontal,
  Sparkles,
  Grid3X3,
  ClipboardList,
  Stethoscope,
  BadgeCheck,
  Star,
  ChevronRight,
  Package,
  Link,
  Bell,
  Settings,
  LogOut,
  CreditCard,
  Bookmark,
  Folder,
  Users,
  Handshake,
  Trophy,
  Target,
  Gift,
  Ticket,
  Download,
  Moon,
  Mail,
  HelpCircle,
  Mic,
  Video,
  SkipBack,
  Pause,
  SkipForward,
  Dumbbell,
  GraduationCap,
  Radio,
  Camera,
  Music,
  Newspaper,
  BriefcaseBusiness,
  Leaf,
  FlaskConical,
  Pill,
  Zap,
  Rocket,
  Lightbulb,
  Wind,
} from "lucide-react";

const ICONS: Record<string, ComponentType<{ className?: string }>> = {
  activity: Activity,
  home: Home,
  image: Image,
  info: Info,
  user: User,
  calendar: Calendar,
  "file-text": FileText,
  search: Search,
  globe: Globe,
  cart: ShoppingCart,
  shop: ShoppingBag,
  restaurant: UtensilsCrossed,
  church: Church,
  realestate: Building2,
  healthcare: HeartPulse,
  heart: Heart,
  map: MapPin,
  phone: Phone,
  directions: Navigation,
  more: MoreHorizontal,
  sparkles: Sparkles,
  grid: Grid3X3,
  list: ClipboardList,
  doctors: Stethoscope,
  verified: BadgeCheck,
  star: Star,
  "chevron-right": ChevronRight,
  package: Package,
  link: Link,
  bell: Bell,
  settings: Settings,
  "log-out": LogOut,
  "credit-card": CreditCard,
  bookmark: Bookmark,
  folder: Folder,
  users: Users,
  handshake: Handshake,
  trophy: Trophy,
  target: Target,
  gift: Gift,
  ticket: Ticket,
  download: Download,
  moon: Moon,
  mail: Mail,
  "help-circle": HelpCircle,
  mic: Mic,
  video: Video,
  "skip-back": SkipBack,
  pause: Pause,
  "skip-forward": SkipForward,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  radio: Radio,
  camera: Camera,
  music: Music,
  wind: Wind,
  book: BookOpen,
  timer: Timer,
  trend: TrendingUp,
  megaphone: Megaphone,
  flame: Flame,
  footprints: Footprints,
  scissors: Scissors,
  palette: Palette,
  paintbrush: Paintbrush,
  cloud: Cloud,
  crown: Crown,
  chart: BarChart3,
  film: Film,
  newspaper: Newspaper,
  briefcase: BriefcaseBusiness,
  leaf: Leaf,
  flask: FlaskConical,
  pill: Pill,
  zap: Zap,
  rocket: Rocket,
  lightbulb: Lightbulb,
};

export function NativeIcon({
  name,
  className,
}: {
  name?: string;
  className?: string;
}) {
  const key = String(name || "").trim().toLowerCase();
  const Icon = ICONS[key] || FileText;
  return <Icon className={className} />;
}

export const NATIVE_ICON_IDS = Object.keys(ICONS);
