# GitHub Actions workflow for iOS builds
# Save this file as: .github/workflows/ios-build.yml in your applyn-ios-builder repo

name: Build iOS App

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'App ID'
        required: true
      app_name:
        description: 'App Name'
        required: true
      bundle_id:
        description: 'Bundle ID (e.g., com.applyn.myapp)'
        required: true
      website_url:
        description: 'Website URL to wrap'
        required: true
      version_code:
        description: 'Version Code'
        required: true
        default: '1'
      callback_url:
        description: 'Callback URL for build completion'
        required: true

env:
  APP_ID: ${{ github.event.inputs.app_id }}
  APP_NAME: ${{ github.event.inputs.app_name }}
  BUNDLE_ID: ${{ github.event.inputs.bundle_id }}
  WEBSITE_URL: ${{ github.event.inputs.website_url }}
  VERSION_CODE: ${{ github.event.inputs.version_code }}
  CALLBACK_URL: ${{ github.event.inputs.callback_url }}

jobs:
  build:
    runs-on: macos-14  # Uses M1 Mac - faster and same cost
    timeout-minutes: 30

    steps:
      - name: Checkout iOS Template
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Update Bundle ID
        run: |
          # Update Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" WebViewApp/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" WebViewApp/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $APP_NAME" WebViewApp/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $VERSION_CODE" WebViewApp/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.$VERSION_CODE" WebViewApp/Info.plist

      - name: Update Website URL
        run: |
          # Replace placeholder URL in ViewController.swift
          sed -i '' "s|__WEBSITE_URL__|$WEBSITE_URL|g" WebViewApp/ViewController.swift
          sed -i '' "s|__APP_NAME__|$APP_NAME|g" WebViewApp/ViewController.swift

      - name: Update Project Bundle ID
        run: |
          # Update bundle identifier in project.pbxproj (replace template placeholder)
          sed -i '' "s|__BUNDLE_ID__|$BUNDLE_ID|g" WebViewApp.xcodeproj/project.pbxproj
          sed -i '' "s|__APP_NAME__|$APP_NAME|g" WebViewApp.xcodeproj/project.pbxproj
          sed -i '' "s|__VERSION_CODE__|$VERSION_CODE|g" WebViewApp.xcodeproj/project.pbxproj
          # Also update Info.plist placeholders
          sed -i '' "s|__BUNDLE_ID__|$BUNDLE_ID|g" WebViewApp/Info.plist
          sed -i '' "s|__APP_NAME__|$APP_NAME|g" WebViewApp/Info.plist
          sed -i '' "s|__VERSION_CODE__|$VERSION_CODE|g" WebViewApp/Info.plist

      - name: Install Apple Certificate
        if: ${{ env.APPLE_CERTIFICATE_BASE64 != '' }}
        env:
          APPLE_CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ github.run_id }}
        run: |
          # Create temporary keychain
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # Import certificate
          echo -n "$APPLE_CERTIFICATE_BASE64" | base64 --decode -o $RUNNER_TEMP/certificate.p12
          security import $RUNNER_TEMP/certificate.p12 -P "$APPLE_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          
          # Allow codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

      - name: Install Provisioning Profile
        if: ${{ env.APPLE_PROVISIONING_PROFILE_BASE64 != '' }}
        env:
          APPLE_PROVISIONING_PROFILE_BASE64: ${{ secrets.APPLE_PROVISIONING_PROFILE_BASE64 }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n "$APPLE_PROVISIONING_PROFILE_BASE64" | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Build iOS App (Unsigned - Simulator)
        if: ${{ env.APPLE_CERTIFICATE_BASE64 == '' }}
        run: |
          xcodebuild -project WebViewApp.xcodeproj \
            -scheme WebViewApp \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build
          
          # Create IPA-like archive for simulator
          mkdir -p build/Payload
          cp -r ~/Library/Developer/Xcode/DerivedData/WebViewApp-*/Build/Products/Release-iphonesimulator/WebViewApp.app build/Payload/
          cd build && zip -r "../$APP_ID.ipa" Payload

      - name: Build iOS App (Signed - Device)
        if: ${{ env.APPLE_CERTIFICATE_BASE64 != '' }}
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          xcodebuild -project WebViewApp.xcodeproj \
            -scheme WebViewApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/WebViewApp.xcarchive \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            archive
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/WebViewApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/
          
          mv build/WebViewApp.ipa "$APP_ID.ipa"

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-${{ env.APP_ID }}
          path: ${{ env.APP_ID }}.ipa
          retention-days: 7

      - name: Notify Callback (Success)
        if: success()
        env:
          IOS_CALLBACK_SECRET: ${{ secrets.IOS_CALLBACK_SECRET }}
        run: |
          curl -X POST "$CALLBACK_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $IOS_CALLBACK_SECRET" \
            -d "{\"appId\": \"$APP_ID\", \"status\": \"success\", \"runId\": \"${{ github.run_id }}\", \"artifactName\": \"ios-app-$APP_ID\"}"

      - name: Notify Callback (Failure)
        if: failure()
        env:
          IOS_CALLBACK_SECRET: ${{ secrets.IOS_CALLBACK_SECRET }}
        run: |
          curl -X POST "$CALLBACK_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $IOS_CALLBACK_SECRET" \
            -d "{\"appId\": \"$APP_ID\", \"status\": \"failure\", \"runId\": \"${{ github.run_id }}\", \"error\": \"Build failed\"}"

      - name: Cleanup Keychain
        if: always()
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db 2>/dev/null || true
